#!/bin/bash

# Navigate to client directory
cd client

# Create .env.production file with environment variables
cat > .env.production << EOF
REACT_APP_GA_TRACKING_ID=$REACT_APP_GA_TRACKING_ID
REACT_APP_API_URL=$REACT_APP_API_URL
REACT_APP_OPENWEATHER_API_KEY=$REACT_APP_OPENWEATHER_API_KEY
REACT_APP_NPS_API_KEY=$REACT_APP_NPS_API_KEY
REACT_APP_ADMIN_PASSWORD=$REACT_APP_ADMIN_PASSWORD
REACT_APP_ADMIN_EMAIL=$REACT_APP_ADMIN_EMAIL
REACT_APP_ENV=$REACT_APP_ENV
REACT_APP_NAME=$REACT_APP_NAME
REACT_APP_DOMAIN=$REACT_APP_DOMAIN
REACT_APP_URL=$REACT_APP_URL
REACT_APP_WEBSITE_URL=$REACT_APP_WEBSITE_URL
EOF

# Run build
npm run build

# Navigate back to root
cd ..
